apiVersion: v1
kind: Service
metadata:
  name: DevOpsProjectCapsone
spec:
  type: LoadBalancer
  selector:
    app: DevOpsProjectCapsone
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: DevOpsProjectCapsone-deploy
spec:
  selector:
    matchLabels:
      app: DevOpsProjectCapsone
  replicas: 3
  template:
    metadata:
      labels:
        app: DevOpsProjectCapsone
    spec:
      containers:
      - name: DevOpsProjectCapsone-pod
        image: a3ajagbe/kubernetes-clusters-demo:devopsprojectpapsone
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10
